# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-XMPP
version:      1.0
version_from: lib/Net/XMPP.pm
installdirs:  site
requires:
    Digest::SHA1:                  1.02
    XML::Stream:                   1.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
