--- #YAML:1.0
name: Net-XMPP
version: 1.02
author:
  - xmpplar
abstract: XMPP Support Library
license: lgpl
resources:
  license: |-
    http://opensource.org/licenses/artistic-license.php
requires:
  Digest::SHA1: 1.02
  XML::Stream: 1.22
provides:
  Net::XMPP:
    file: lib/Net/XMPP.pm
    version: 1.02
  Net::XMPP::Client:
    file: lib/Net/XMPP/Client.pm
  Net::XMPP::Connection:
    file: lib/Net/XMPP/Connection.pm
  Net::XMPP::Debug:
    file: lib/Net/XMPP/Debug.pm
  Net::XMPP::IQ:
    file: lib/Net/XMPP/IQ.pm
  Net::XMPP::JID:
    file: lib/Net/XMPP/JID.pm
  Net::XMPP::Message:
    file: lib/Net/XMPP/Message.pm
  Net::XMPP::Namespaces:
    file: lib/Net/XMPP/Namespaces.pm
  Net::XMPP::Presence:
    file: lib/Net/XMPP/Presence.pm
  Net::XMPP::PrivacyLists:
    file: lib/Net/XMPP/PrivacyLists.pm
  Net::XMPP::Protocol:
    file: lib/Net/XMPP/Protocol.pm
  Net::XMPP::Roster:
    file: lib/Net/XMPP/Roster.pm
  Net::XMPP::Stanza:
    file: lib/Net/XMPP/Stanza.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: |-
    http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
